import os
import sys
import json
import smtplib
from datetime import datetime
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Configuration
BASE_DIR = Path(__file__).parent
WEBSITE_DIR = BASE_DIR
OUTPUT_DIR = BASE_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

# Email config
EMAIL_CONFIG = {
    "smtp_server": "smtp.gmail.com",
    "smtp_port": 587,
    "sender_email": "shellyai2026@gmail.com",
    "sender_password": "ygwkifjjdwhorvje",
}

# Topics to rotate through
TOPICS = [
    "rapamycin",
    "nad-boosters",
    "fasting-protocols",
    "senolytics",
    "metformin",
    "omega-3",
    "sleep-optimization",
    "zone-2-cardio",
    "spermidine",
    "epigenetic-reprogramming"
]

def generate_article(topic):
    """Generate article content - this will be called by the AI agent"""
    # The actual generation is done by the AI model when this script runs
    # For now, we'll create a placeholder that triggers the AI generation
    print(f"Article generation requested for: {topic}")
    print("Note: This script should be run by the OpenClaw agent")
    print("which will use the AI model to generate content.")
    return None

def convert_to_html(markdown_content, title):
    """Convert markdown to HTML"""
    import re
    
    html_content = markdown_content
    
    # Convert headers
    html_content = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_content, flags=re.MULTILINE)
    html_content = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_content, flags=re.MULTILINE)
    html_content = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_content, flags=re.MULTILINE)
    
    # Convert bold and italic
    html_content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_content)
    html_content = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_content)
    
    # Convert paragraphs
    paragraphs = html_content.split('\n\n')
    html_paragraphs = []
    for p in paragraphs:
        if not p.startswith('<h') and p.strip():
            html_paragraphs.append(f'<p>{p}</p>')
        else:
            html_paragraphs.append(p)
    html_content = '\n\n'.join(html_paragraphs)
    
    html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - The Longevity Journal</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="article-page">
        <div class="article-meta-bar">
            <span class="category">Research</span>
            <span class="date">{datetime.now().strftime('%B %d, %Y')}</span>
            <span class="read-time">8 min read</span>
        </div>
        <div class="article-content">
            {html_content}
        </div>
    </div>
</body>
</html>
"""
    return html_template

def save_article_locally(title, html_content, topic):
    """Save article to local file"""
    article_filename = f"{topic}-{datetime.now().strftime('%Y%m%d')}.html"
    article_path = WEBSITE_DIR / article_filename
    with open(article_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"Article saved: {article_path}")
    return article_filename

def run_pipeline():
    """Run the full weekly pipeline"""
    print("=" * 60)
    print("THE LONGEVITY JOURNAL - WEEKLY PIPELINE")
    print(f"Starting: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # Select topic based on week number
    topic = TOPICS[datetime.now().isocalendar()[1] % len(TOPICS)]
    print(f"\n1. Selected topic: {topic}")
    print("\n2. Ready for AI generation...")
    print("   (The OpenClaw agent should generate content and pass it to this pipeline)")
    
    return topic

def process_generated_article(topic, article_content):
    """Process an article that was generated by the AI"""
    if not article_content:
        print("FAILED: No article content provided")
        return False
    
    print(f"\n3. Processing article: {len(article_content)} characters")
    
    # Convert to HTML
    print("\n4. Converting to HTML...")
    title = f"The Science of {topic.replace('-', ' ').title()}"
    html_content = convert_to_html(article_content, title)
    
    # Save article
    print("\n5. Saving article...")
    article_filename = save_article_locally(title, html_content, topic)
    
    # Update index
    print("\n6. Updating website index...")
    update_index(article_filename, title)
    
    print("\n" + "=" * 60)
    print("ARTICLE PROCESSED SUCCESSFULLY!")
    print("=" * 60)
    return True

def update_index(article_filename, title):
    """Update index.html to include new article"""
    try:
        index_path = WEBSITE_DIR / "index.html"
        if index_path.exists():
            with open(index_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            new_link = f'<li><a href="{article_filename}">{title}</a></li>'
            content = content.replace('</ul>', f'{new_link}\n</ul>')
            
            with open(index_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print("Index updated successfully")
        else:
            print("Warning: index.html not found")
    except Exception as e:
        print(f"Error updating index: {e}")

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--test":
        print("Running in TEST mode...")
        topic = run_pipeline()
        print(f"\nTest complete. Ready to generate article about: {topic}")
        print("Pass --article 'content' to process generated content")
    else:
        topic = run_pipeline()
        print(f"\nSelected topic: {topic}")
        print("Waiting for AI-generated content...")
